services:
  thaddeus-portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thaddeus-portfolio-production
    restart: unless-stopped

    ports:
      - "127.0.0.1:8005:8000"

    env_file:
      - .env

    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
      - ./db.sqlite3:/app/db.sqlite3

    command: >
      sh -c "
        python manage.py collectstatic --noinput &&
        python manage.py migrate dashboard &&
        python manage.py migrate django_portfolio &&
        python manage.py migrate &&
        gunicorn django_portfolio.wsgi:application --bind 0.0.0.0 --workers 2 --timeout 120 --access-logfile - --error-logfile -
      "
  nginx:
    image: nginx:alpine
    container_name: thaddeus-portfolio-static
    restart: unless-stopped

    ports:
      - "127.0.0.1:8006:80"

    volumes:
      - ./staticfiles:/usr/share/nginx/html/static:ro
      - ./media:/usr/share/nginx/html/media:ro
