# Generated by Django 5.2.17 on 2026-09-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='media/blogs'),
        ),
        migrations.AlterField(
            model_name='language',
            name='image',
            field=models.ImageField(upload_to='media/languages'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='media/projects'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(upload_to='media/testimonials'),
        ),
        migrations.AlterField(
            model_name='uploadedasset',
            name='file',
            field=models.FileField(upload_to='media/assets'),
        ),
    ]
