# Generated by Django 5.2.17 on 2026-09-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_blog_image_alter_language_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='blogs/'),
        ),
        migrations.AlterField(
            model_name='language',
            name='image',
            field=models.ImageField(upload_to='languages/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(upload_to='testimonials/'),
        ),
        migrations.AlterField(
            model_name='uploadedasset',
            name='file',
            field=models.FileField(upload_to='assets/'),
        ),
    ]
